dist: xenial

language: minimal

services:
  - docker

addons:
  apt:
    update: true
    packages:
      - docker-ce

before_install:
  - docker --version
  - ls
  - whoami

script:
  - lsb_release -a

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#onox"
    use_notice: false
    on_success: always
    on_failure: always
