dist: xenial

language: minimal

services:
  - docker

script:
  - docker pull tomekw/ada-gnat:7:3:0
  - docker run -v $(pwd):/app tomekw/ada-gnat:7:3:0 sh -c "apt install -y --no-install-recommends gprbuild libahven6-dev lcov"
  - ls

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#onox"
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{result}"
      - "%{build_url}"
    use_notice: true
    on_success: always
    on_failure: always
