dist: xenial

language: minimal

services:
  - docker

before_install:
  - docker pull tomekw/ada-gnat:7.3.0

script:
  - docker run -v $(pwd):/app tomekw/ada-gnat:7.3.0 sh -c "apt install -y --no-install-recommends gprbuild libahven6-dev lcov;gnatmake hello_world.adb;./hello_world"

after_success:
  - echo "success!"

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#onox"
    template:
      - "%{repository_slug}#%{build_number} - %{branch}/%{commit} by %{author}: %{result}"
      - "%{build_url}"
    on_success: always
    on_failure: always
