dist: xenial

language: minimal

services:
  - docker

before_install:
  - docker --version

script:
  - lsb_release -a

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#onox"
    use_notice: true
    on_success: always
    on_failure: always
