dist: xenial

language: minimal

services:
  - docker

script:
  - docker run -v $(pwd):/app tomekw/ada-gnat:7.3.0 sh -c "apt install -y --no-install-recommends gprbuild libahven6-dev lcov;gnat --version;gnatls -v"

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#onox"
    template:
      - "%{repository_slug}#%{build_number} - %{commit} by %{author} on %{branch}: %{message}"
      - "%{build_url}"
    on_success: always
    on_failure: always
